export enum MilestoneState {
  DEFINE = 'DEFINED',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  FUNDED = 'FUNDED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  IN_REVISION = 'IN_REVISION',
  APPROVED = 'APPROVED',
  RELEASED = 'RELEASED',
  DISPUTED = 'DISPUTED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
}
