export enum TransactionType {
  TOP_UP = 'TOP_UP',
  SUBSCRIPTION = 'SUBSCRIPTION',
  ESCROW_LOCK = 'ESCROW_LOCK',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  PLATFORM_FEE = 'PLATFORM_FEE',
  ESCROW_REFUND = 'ESCROW_REFUND',
  ESCROW_SPLIT = 'ESCROW_SPLIT',
  WITHDRAWAL = 'WITHDRAWAL',
}
